services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: philahomes
      POSTGRES_PASSWORD: philahomes
      POSTGRES_DB: philahomes
    ports:
      - '5432:5432'
    volumes:
      - philahomes_pgdata:/var/lib/postgresql/data

volumes:
  philahomes_pgdata:
